// ignore_for_file: constant_identifier_names

import 'package:flutter/material.dart';

/// Flutter icons WeatherIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';

  static const IconData moon_weather_snow_night = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_forward = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData morning_sunrise_sun_weather = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData night_weather_clouds_storm_rain_moon = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData rain_cloud_drizzel_weather = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData sand_weather_sandstorm_sun_day = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData sand_weather_storm_sandstorm = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData storm_weather_night_clouds = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData storm_weather_sandstorm_sand_cloud = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData storm_weather_thunder_clouds_rain = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sunny_rain_cloudy_weather_clouds = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sunny_weather_clouds_storm = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData weather_clouds_fog_foggy = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData weather_forecast_temperature_thermometer = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData weather_moon_moonrise_night = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData weather_moonset_moon_morning = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData weather_night_moon_moonlight = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData weather_rain_storm_night = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData weather_sun_sunny_temperature = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData weather_sunset_sun_evening = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData rain_storm_shower_weather = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData wind_weather_cloudy_storm = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData windy_cloudy_storm_wind_weather = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData winter_snow_clouds_weather = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData winter_snowflake_christmas_xmas_weather_snow = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData clouds_sun_sunny_weather = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData cloudy_weather_clouds_cloud = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData foggy_weather_fog_clouds_cloudy = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData hail_weather_hailstone_clouds_snow = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData cloudy_weather_forecast_rain_clouds = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData hurricane_weather_tornado_storm = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData moon_night_weather_foggy_fog = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData moon_weather_clouds_cloudy = IconData(0xe820, fontFamily: _kFontFam);
}
